fp = open("result.txt","w")
fp.write('sno \t sname \t sm1 \t sm2 \t sm3 \t stot\n')
fp.close()
ch='y'
while ch=='y':
    sno = input("Enter student no:")
    sname = input("Enter student name:")
    sm1 = input("Enter s1 marks:")
    sm2 = input("Enter s2 marks:")
    sm3 = input("Enter s3 marks:")
    tot= int(sm1)+int(sm2)+int(sm3)
    stot = str(tot)
    fp = open("result.txt","a+")
    fp.write(sno+'\t'+sname+'\t'+sm1+'\t'+sm2+'\t'+sm3+'\t'+stot+'\n')
    ch=input("Do u wanna continue (y/n)")
fp.close()
fp=open("result.txt","r")
v=fp.readline()
while v!='':
    print(v)
    v=fp.readline()
fp.close()
