rs=open("result1.txt","w")
rs.write("sno \t sname \t m1 \t m2 \t m3 \t tot \t \n")
rs.close()
ch='y'
while ch =="y":
    sno = input("Enter student no")
    sname = input("Enter student name")
    m1 = input("Enter marks1")
    m2 = input("Enter marks2")
    m3 = input("Enter marks3")
    tot = int(m1)+int(m2)+int(m3)
    stot = str(tot)
    #rs.open("result1.txt",'a+')
    rs=open("result1.txt",'a+')
    rs.write(sno + '\t' + sname + '\t' + m1 + '\t' + m2 + '\t' + m3 + '\t' + stot + '\n')
    ch = input("Do you want to continue y/n")
rs.close()
print("\n \n")
rs=open("result1.txt","r")
v=rs.readline()
while v!='':
    print(v)
    v=rs.readline()
rs.close()
