fp = open("result.txt","w")
fp.write('s.no \t sname \t sm1 \t sm2 \t sm3')
fp.close()
ch = 'y'
while ch=='y':
    sno = int(input("Enter roll no :"))
    sname = input("Enter name :")
    sm1 = input("marks1 :")
    sm2 = input("marks2 : ")
    sm3 = input("marks3 :")
    fp = open("result.txt","a+")
    fp.write(sno+'\t'+sname+'\t'+sm1+'\t'+sm2+'\t'+ sm3)
    ch = input("continue y/n")
fp.close()
fp = open("result.txt","r")
v = fp.readline()
while v!=' ':
    print(v)
    v=fp.readline()
fp.close()
